import { useState, useEffect, useCallback } from "react";
import {
  Plus,
  Search,
  Calendar,
  Clock,
  Check,
  X,
  Trash2,
  ChevronLeft,
  ChevronRight,
  List,
  Grid3X3,
  RefreshCw,
  Eye,
  MessageSquare,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { appointmentsApi, Appointment as ApiAppointment } from "@/lib/api-client";
import { useToast } from "@/hooks/use-toast";

interface Appointment {
  id: string;
  autoGeneratedId: string;
  clientName: string;
  clientPhone: string;
  serviceName: string;
  providerName: string;
  date: string;
  time: string;
  duration: number;
  status: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED" | "NO_SHOW" | "RESCHEDULED";
  notes?: string;
  createdAt: string;
}

const serviceTypeLabels: Record<string, string> = {
  COUNSELLING: "Counselling",
  DENTAL: "Dental Care",
  FITNESS: "Fitness & Gym",
  GYM: "Fitness & Gym",
  SKINCARE: "Skin Care",
  REHAB: "Rehabilitation",
  NUTRITION: "Nutrition",
  ELITE_SPORT: "Elite Sports",
  ELITE: "Elite Sports",
  SPA: "Spa & Massage",
  GENERAL: "General",
};

const statusColors: Record<string, string> = {
  PENDING: "bg-yellow-100 text-yellow-800",
  APPROVED: "bg-green-100 text-green-800",
  CONFIRMED: "bg-green-100 text-green-800",
  CANCELLED: "bg-red-100 text-red-800",
  COMPLETED: "bg-blue-100 text-blue-800",
  RESCHEDULED: "bg-purple-100 text-purple-800",
};

function transformAppointment(raw: ApiAppointment): Appointment {
  const scheduledDate = raw.scheduledAt ? new Date(raw.scheduledAt) : null;
  const patient = raw.patient;
  return {
    id: raw.id,
    autoGeneratedId: raw.reference || `APT-${raw.id.slice(0, 6).toUpperCase()}`,
    clientName: patient ? `${patient.firstName} ${patient.lastName}` : "Unknown",
    clientPhone: patient?.phone || "—",
    serviceName: raw.service?.name || raw.type?.replace(/_/g, " ") || "General",
    providerName: raw.provider?.name || "—",
    date: scheduledDate ? scheduledDate.toLocaleDateString() : "—",
    time: scheduledDate ? scheduledDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—",
    duration: raw.duration ?? 60,
    status: raw.status as Appointment["status"],
    notes: raw.notes,
    createdAt: raw.createdAt,
  };
}

const AppointmentList = () => {
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [serviceFilter, setServiceFilter] = useState("all");
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  const [view, setView] = useState<"list" | "calendar">("list");
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [selectedAppointment, setSelectedAppointment] = useState<Appointment | null>(null);
  const [isRescheduleDialogOpen, setIsRescheduleDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);

  const [rescheduleForm, setRescheduleForm] = useState({ date: "", time: "", reason: "" });

  const itemsPerPage = 10;

  const fetchAppointments = useCallback(async () => {
    setLoading(true);
    try {
      const response = await appointmentsApi.getAll({
        page: currentPage,
        limit: itemsPerPage,
        status: statusFilter !== "all" ? statusFilter : undefined,
      });

      const transformed = (response.data || []).map(transformAppointment);

      const filtered = searchQuery
        ? transformed.filter(
            (a) =>
              a.clientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
              a.autoGeneratedId.toLowerCase().includes(searchQuery.toLowerCase()) ||
              a.serviceName.toLowerCase().includes(searchQuery.toLowerCase())
          )
        : transformed;

      setAppointments(filtered);
      setTotal(response.meta?.total ?? filtered.length);
      setTotalPages(response.meta?.totalPages ?? 1);
    } catch (error) {
      console.error("Failed to fetch appointments:", error);
      toast({ title: "Error", description: "Failed to load appointments", variant: "destructive" });
      setAppointments([]);
    } finally {
      setLoading(false);
    }
  }, [currentPage, statusFilter, serviceFilter, searchQuery, toast]);

  useEffect(() => {
    fetchAppointments();
  }, [fetchAppointments]);

  const handleApprove = async (apt: Appointment) => {
    setActionLoading(apt.id);
    try {
      await appointmentsApi.confirm(apt.id);
      setAppointments((prev) => prev.map((a) => (a.id === apt.id ? { ...a, status: "CONFIRMED" } : a)));
      toast({ title: "Appointment confirmed" });
    } catch {
      toast({ title: "Failed to confirm appointment", variant: "destructive" });
    } finally {
      setActionLoading(null);
    }
  };

  const handleReject = async (apt: Appointment) => {
    setActionLoading(apt.id);
    try {
      await appointmentsApi.cancel(apt.id);
      setAppointments((prev) => prev.map((a) => (a.id === apt.id ? { ...a, status: "CANCELLED" } : a)));
      toast({ title: "Appointment cancelled" });
    } catch {
      toast({ title: "Failed to cancel appointment", variant: "destructive" });
    } finally {
      setActionLoading(null);
    }
  };

  const handleComplete = async (apt: Appointment) => {
    setActionLoading(apt.id);
    try {
      await appointmentsApi.complete(apt.id);
      setAppointments((prev) => prev.map((a) => (a.id === apt.id ? { ...a, status: "COMPLETED" } : a)));
      toast({ title: "Appointment marked complete" });
    } catch {
      toast({ title: "Failed to update appointment", variant: "destructive" });
    } finally {
      setActionLoading(null);
    }
  };

  const submitReschedule = async () => {
    if (!selectedAppointment) return;
    setActionLoading(selectedAppointment.id);
    try {
      const scheduledAt = `${rescheduleForm.date}T${rescheduleForm.time}:00`;
      await appointmentsApi.reschedule(selectedAppointment.id, scheduledAt, rescheduleForm.reason);
      setAppointments((prev) =>
        prev.map((a) =>
          a.id === selectedAppointment.id
            ? { ...a, date: rescheduleForm.date, time: rescheduleForm.time, status: "RESCHEDULED" }
            : a
        )
      );
      toast({ title: "Appointment rescheduled" });
    } catch {
      toast({ title: "Failed to reschedule", variant: "destructive" });
    } finally {
      setActionLoading(null);
      setIsRescheduleDialogOpen(false);
    }
  };

  const submitDelete = async () => {
    if (!selectedAppointment) return;
    setActionLoading(selectedAppointment.id);
    try {
      await appointmentsApi.cancel(selectedAppointment.id, "Deleted by admin");
      setAppointments((prev) => prev.filter((a) => a.id !== selectedAppointment.id));
      setTotal((t) => t - 1);
      toast({ title: "Appointment removed" });
    } catch {
      toast({ title: "Failed to remove appointment", variant: "destructive" });
    } finally {
      setActionLoading(null);
      setIsDeleteDialogOpen(false);
    }
  };

  const pendingCount = appointments.filter((a) => a.status === "PENDING").length;
  const approvedCount = appointments.filter((a) => a.status === "APPROVED" || a.status === "CONFIRMED").length;
  const completedCount = appointments.filter((a) => a.status === "COMPLETED").length;
  const cancelledCount = appointments.filter((a) => a.status === "CANCELLED").length;

  return (
    <div className="p-6 lg:p-8 space-y-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl lg:text-3xl font-bold">Appointments</h1>
          <p className="text-muted-foreground mt-1">Manage all client appointments</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={fetchAppointments} disabled={loading}>
            <RefreshCw className={`w-4 h-4 mr-2 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
          <Button>
            <Plus className="w-4 h-4 mr-2" />
            Schedule New
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-5">
        {[
          { label: "Total", value: total, color: "", icon: Calendar },
          { label: "Pending", value: pendingCount, color: "text-yellow-600", icon: Clock },
          { label: "Confirmed", value: approvedCount, color: "text-green-600", icon: Check },
          { label: "Completed", value: completedCount, color: "text-blue-600", icon: Check },
          { label: "Cancelled", value: cancelledCount, color: "text-red-600", icon: X },
        ].map(({ label, value, color, icon: Icon }) => (
          <Card key={label}>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">{label}</p>
                  <p className={`text-2xl font-bold ${color}`}>{loading ? "—" : value}</p>
                </div>
                <Icon className="w-8 h-8 text-muted-foreground/20" />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search by client or appointment ID..."
                className="pl-9"
                value={searchQuery}
                onChange={(e) => { setSearchQuery(e.target.value); setCurrentPage(1); }}
              />
            </div>
            <div className="flex gap-2">
              <Select value={statusFilter} onValueChange={(v) => { setStatusFilter(v); setCurrentPage(1); }}>
                <SelectTrigger className="w-[150px]">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="PENDING">Pending</SelectItem>
                  <SelectItem value="CONFIRMED">Confirmed</SelectItem>
                  <SelectItem value="COMPLETED">Completed</SelectItem>
                  <SelectItem value="CANCELLED">Cancelled</SelectItem>
                  <SelectItem value="RESCHEDULED">Rescheduled</SelectItem>
                </SelectContent>
              </Select>
              <Select value={serviceFilter} onValueChange={(v) => { setServiceFilter(v); setCurrentPage(1); }}>
                <SelectTrigger className="w-[180px]">
                  <SelectValue placeholder="Service Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Services</SelectItem>
                  <SelectItem value="COUNSELLING">Counselling</SelectItem>
                  <SelectItem value="DENTAL">Dental Care</SelectItem>
                  <SelectItem value="FITNESS">Fitness & Gym</SelectItem>
                  <SelectItem value="SPA">Spa & Massage</SelectItem>
                  <SelectItem value="REHAB">Rehabilitation</SelectItem>
                  <SelectItem value="NUTRITION">Nutrition</SelectItem>
                  <SelectItem value="ELITE_SPORT">Elite Sports</SelectItem>
                </SelectContent>
              </Select>
              <div className="flex border rounded-lg">
                <Button variant={view === "list" ? "default" : "ghost"} size="icon" onClick={() => setView("list")}>
                  <List className="w-4 h-4" />
                </Button>
                <Button variant={view === "calendar" ? "default" : "ghost"} size="icon" onClick={() => setView("calendar")}>
                  <Grid3X3 className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Tabs value={view} onValueChange={(v) => setView(v as "list" | "calendar")}>
        <TabsList className="hidden">
          <TabsTrigger value="list">List</TabsTrigger>
          <TabsTrigger value="calendar">Calendar</TabsTrigger>
        </TabsList>

        <TabsContent value="list">
          <Card>
            <CardContent className="pt-6">
              {loading ? (
                <div className="flex items-center justify-center h-40">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
                </div>
              ) : appointments.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">No appointments found</div>
              ) : (
                <div className="rounded-md border">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>ID</TableHead>
                        <TableHead>Client</TableHead>
                        <TableHead>Service</TableHead>
                        <TableHead>Date & Time</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {appointments.map((apt) => (
                        <TableRow key={apt.id}>
                          <TableCell>
                            <div>
                              <p className="font-medium">{apt.autoGeneratedId}</p>
                              <p className="text-xs text-muted-foreground">
                                {new Date(apt.createdAt).toLocaleDateString()}
                              </p>
                            </div>
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-3">
                              <Avatar>
                                <AvatarFallback className="bg-primary/10 text-primary">
                                  {apt.clientName.split(" ").map((n) => n[0]).join("").toUpperCase().slice(0, 2)}
                                </AvatarFallback>
                              </Avatar>
                              <div>
                                <p className="font-medium">{apt.clientName}</p>
                                <p className="text-xs text-muted-foreground">{apt.clientPhone}</p>
                              </div>
                            </div>
                          </TableCell>
                          <TableCell>
                            <Badge variant="outline">{apt.serviceName}</Badge>
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2 text-sm">
                              <Calendar className="w-4 h-4 text-muted-foreground" />
                              <span>{apt.date}</span>
                            </div>
                            <div className="flex items-center gap-2 text-xs text-muted-foreground">
                              <Clock className="w-3 h-3" />
                              <span>{apt.time}</span>
                            </div>
                          </TableCell>
                          <TableCell>
                            <Badge className={statusColors[apt.status] || "bg-gray-100 text-gray-800"}>
                              {apt.status.charAt(0) + apt.status.slice(1).toLowerCase()}
                            </Badge>
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-1">
                              {apt.status === "PENDING" && (
                                <>
                                  <Button
                                    variant="ghost"
                                    size="icon"
                                    className="text-green-600 hover:text-green-700 hover:bg-green-50"
                                    onClick={() => handleApprove(apt)}
                                    disabled={actionLoading === apt.id}
                                    title="Confirm"
                                  >
                                    <Check className="w-4 h-4" />
                                  </Button>
                                  <Button
                                    variant="ghost"
                                    size="icon"
                                    className="text-red-600 hover:text-red-700 hover:bg-red-50"
                                    onClick={() => handleReject(apt)}
                                    disabled={actionLoading === apt.id}
                                    title="Cancel"
                                  >
                                    <X className="w-4 h-4" />
                                  </Button>
                                </>
                              )}
                              {(apt.status === "APPROVED" || apt.status === "CONFIRMED") && (
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="text-blue-600 hover:text-blue-700 hover:bg-blue-50"
                                  onClick={() => handleComplete(apt)}
                                  disabled={actionLoading === apt.id}
                                  title="Mark Complete"
                                >
                                  <Check className="w-4 h-4" />
                                </Button>
                              )}
                              <Button
                                variant="ghost"
                                size="icon"
                                onClick={() => { setSelectedAppointment(apt); setIsViewDialogOpen(true); }}
                                title="View Details"
                              >
                                <Eye className="w-4 h-4" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="text-purple-600 hover:text-purple-700 hover:bg-purple-50"
                                onClick={() => {
                                  setSelectedAppointment(apt);
                                  setRescheduleForm({ date: apt.date, time: apt.time, reason: "" });
                                  setIsRescheduleDialogOpen(true);
                                }}
                                title="Reschedule"
                              >
                                <RefreshCw className="w-4 h-4" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="text-red-600 hover:text-red-700 hover:bg-red-50"
                                onClick={() => { setSelectedAppointment(apt); setIsDeleteDialogOpen(true); }}
                                title="Remove"
                              >
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}

              {totalPages > 1 && (
                <div className="flex items-center justify-between mt-4">
                  <p className="text-sm text-muted-foreground">
                    Showing {(currentPage - 1) * itemsPerPage + 1} to{" "}
                    {Math.min(currentPage * itemsPerPage, total)} of {total} appointments
                  </p>
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="icon" onClick={() => setCurrentPage(currentPage - 1)} disabled={currentPage === 1}>
                      <ChevronLeft className="w-4 h-4" />
                    </Button>
                    {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                      <Button
                        key={page}
                        variant={currentPage === page ? "default" : "outline"}
                        size="icon"
                        onClick={() => setCurrentPage(page)}
                        className="w-8 h-8"
                      >
                        {page}
                      </Button>
                    ))}
                    <Button variant="outline" size="icon" onClick={() => setCurrentPage(currentPage + 1)} disabled={currentPage === totalPages}>
                      <ChevronRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="calendar">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Calendar View</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-7 gap-1">
                {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
                  <div key={day} className="text-center text-sm font-medium p-2">{day}</div>
                ))}
                {Array.from({ length: 35 }, (_, i) => {
                  const day = i - 2;
                  const isCurrentMonth = day > 0 && day <= 31;
                  const dayAppointments = isCurrentMonth
                    ? appointments.filter((a) => new Date(a.date).getDate() === day)
                    : [];
                  return (
                    <div
                      key={i}
                      className={`min-h-[120px] p-2 border rounded-lg ${isCurrentMonth ? "bg-card" : "bg-muted/30"}`}
                    >
                      {isCurrentMonth && (
                        <>
                          <span className="text-sm font-medium">{day}</span>
                          <div className="mt-1 space-y-1">
                            {dayAppointments.slice(0, 3).map((apt) => (
                              <div
                                key={apt.id}
                                className={`text-xs p-1 rounded truncate ${statusColors[apt.status] || "bg-gray-100"}`}
                                title={`${apt.clientName} - ${apt.time}`}
                              >
                                {apt.clientName}
                              </div>
                            ))}
                            {dayAppointments.length > 3 && (
                              <div className="text-xs text-muted-foreground">+{dayAppointments.length - 3} more</div>
                            )}
                          </div>
                        </>
                      )}
                    </div>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* View Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Appointment Details</DialogTitle>
          </DialogHeader>
          {selectedAppointment && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                {[
                  ["Appointment ID", selectedAppointment.autoGeneratedId],
                  ["Status", null],
                  ["Client Name", selectedAppointment.clientName],
                  ["Client Phone", selectedAppointment.clientPhone],
                  ["Provider", selectedAppointment.providerName],
                  ["Service", selectedAppointment.serviceName],
                  ["Duration", `${selectedAppointment.duration} minutes`],
                  ["Date", selectedAppointment.date],
                  ["Time", selectedAppointment.time],
                ].map(([key, val]) => (
                  <div key={key as string}>
                    <Label className="text-muted-foreground">{key}</Label>
                    {key === "Status" ? (
                      <p>
                        <Badge className={statusColors[selectedAppointment.status] || ""}>
                          {selectedAppointment.status}
                        </Badge>
                      </p>
                    ) : (
                      <p className="font-medium">{val as string}</p>
                    )}
                  </div>
                ))}
              </div>
              {selectedAppointment.notes && (
                <div>
                  <Label className="text-muted-foreground">Notes</Label>
                  <p className="font-medium">{selectedAppointment.notes}</p>
                </div>
              )}
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsViewDialogOpen(false)}>Close</Button>
            <Button variant="outline">
              <MessageSquare className="w-4 h-4 mr-2" />
              Message Client
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reschedule Dialog */}
      <Dialog open={isRescheduleDialogOpen} onOpenChange={setIsRescheduleDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reschedule Appointment</DialogTitle>
            <DialogDescription>
              Reschedule appointment for {selectedAppointment?.clientName}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="reschedule-date">New Date</Label>
                <Input
                  id="reschedule-date"
                  type="date"
                  value={rescheduleForm.date}
                  onChange={(e) => setRescheduleForm({ ...rescheduleForm, date: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="reschedule-time">New Time</Label>
                <Input
                  id="reschedule-time"
                  type="time"
                  value={rescheduleForm.time}
                  onChange={(e) => setRescheduleForm({ ...rescheduleForm, time: e.target.value })}
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="reschedule-reason">Reason</Label>
              <Textarea
                id="reschedule-reason"
                value={rescheduleForm.reason}
                onChange={(e) => setRescheduleForm({ ...rescheduleForm, reason: e.target.value })}
                placeholder="Reason for rescheduling..."
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsRescheduleDialogOpen(false)}>Cancel</Button>
            <Button onClick={submitReschedule} disabled={!rescheduleForm.date || !rescheduleForm.time || actionLoading !== null}>
              <RefreshCw className="w-4 h-4 mr-2" />
              Reschedule
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Remove Appointment</DialogTitle>
            <DialogDescription>
              Are you sure you want to remove this appointment? This will cancel it.
            </DialogDescription>
          </DialogHeader>
          {selectedAppointment && (
            <div className="p-4 bg-muted rounded-lg text-sm grid grid-cols-2 gap-2">
              <span className="text-muted-foreground">ID:</span>
              <span className="font-medium">{selectedAppointment.autoGeneratedId}</span>
              <span className="text-muted-foreground">Client:</span>
              <span className="font-medium">{selectedAppointment.clientName}</span>
              <span className="text-muted-foreground">Date:</span>
              <span className="font-medium">{selectedAppointment.date}</span>
              <span className="text-muted-foreground">Time:</span>
              <span className="font-medium">{selectedAppointment.time}</span>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDeleteDialogOpen(false)}>Cancel</Button>
            <Button variant="destructive" onClick={submitDelete} disabled={actionLoading !== null}>
              <Trash2 className="w-4 h-4 mr-2" />
              Remove
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default AppointmentList;
