import { useState } from "react";
import {
  Plus,
  Search,
  Calendar,
  Clock,
  Check,
  X,
  Edit,
  Trash2,
  ChevronLeft,
  ChevronRight,
  List,
  Grid3X3,
  RefreshCw,
  MoreVertical,
  Eye,
  MessageSquare,
  User,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";

interface Appointment {
  id: string;
  autoGeneratedId: string;
  clientId: string;
  clientName: string;
  clientEmail: string;
  clientPhone: string;
  serviceType: string;
  providerId: string;
  providerName: string;
  date: string;
  time: string;
  duration: number;
  status: "PENDING" | "APPROVED" | "CANCELLED" | "COMPLETED" | "RESCHEDULED";
  notes?: string;
  createdAt: string;
}

const mockAppointments: Appointment[] = [
  {
    id: "1",
    autoGeneratedId: "TH-APT-001",
    clientId: "TH-CL-001",
    clientName: "John Doe",
    clientEmail: "john@example.com",
    clientPhone: "+234 801 234 5678",
    serviceType: "COUNSELLING",
    providerId: "TH-SP-001",
    providerName: "Dr. Sarah Johnson",
    date: "2024-01-15",
    time: "10:00 AM",
    duration: 60,
    status: "APPROVED",
    notes: "Initial consultation - client is seeking anxiety management",
    createdAt: "2024-01-10T10:30:00Z",
  },
  {
    id: "2",
    autoGeneratedId: "TH-APT-002",
    clientId: "TH-CL-002",
    clientName: "Jane Smith",
    clientEmail: "jane@example.com",
    clientPhone: "+234 801 234 5679",
    serviceType: "DENTAL",
    providerId: "TH-SP-002",
    providerName: "Dr. Michael Chen",
    date: "2024-01-15",
    time: "11:30 AM",
    duration: 45,
    status: "PENDING",
    notes: "Teeth whitening session",
    createdAt: "2024-01-11T14:20:00Z",
  },
  {
    id: "3",
    autoGeneratedId: "TH-APT-003",
    clientId: "TH-CL-003",
    clientName: "Mike Johnson",
    clientEmail: "mike@example.com",
    clientPhone: "+234 801 234 5680",
    serviceType: "GYM",
    providerId: "TH-SP-003",
    providerName: "Coach James Williams",
    date: "2024-01-15",
    time: "02:00 PM",
    duration: 90,
    status: "APPROVED",
    notes: "Personal training session - focus on upper body",
    createdAt: "2024-01-12T09:15:00Z",
  },
  {
    id: "4",
    autoGeneratedId: "TH-APT-004",
    clientId: "TH-CL-004",
    clientName: "Sarah Williams",
    clientEmail: "sarah@example.com",
    clientPhone: "+234 801 234 5681",
    serviceType: "SPA",
    providerId: "TH-SP-008",
    providerName: "Therapist Maria Garcia",
    date: "2024-01-16",
    time: "09:00 AM",
    duration: 60,
    status: "PENDING",
    notes: "Aromatherapy massage for stress relief",
    createdAt: "2024-01-13T16:45:00Z",
  },
  {
    id: "5",
    autoGeneratedId: "TH-APT-005",
    clientId: "TH-CL-005",
    clientName: "Emily Brown",
    clientEmail: "emily@example.com",
    clientPhone: "+234 801 234 5682",
    serviceType: "REHAB",
    providerId: "TH-SP-005",
    providerName: "Therapist Robert Taylor",
    date: "2024-01-16",
    time: "11:00 AM",
    duration: 45,
    status: "APPROVED",
    notes: "Post-injury rehabilitation session",
    createdAt: "2024-01-14T11:00:00Z",
  },
  {
    id: "6",
    autoGeneratedId: "TH-APT-006",
    clientId: "TH-CL-006",
    clientName: "David Wilson",
    clientEmail: "david@example.com",
    clientPhone: "+234 801 234 5683",
    serviceType: "COUNSELLING",
    providerId: "TH-SP-001",
    providerName: "Dr. Sarah Johnson",
    date: "2024-01-14",
    time: "03:00 PM",
    duration: 60,
    status: "COMPLETED",
    notes: "Session 8 - Progress review",
    createdAt: "2024-01-08T10:00:00Z",
  },
  {
    id: "7",
    autoGeneratedId: "TH-APT-007",
    clientId: "TH-CL-007",
    clientName: "Lisa Anderson",
    clientEmail: "lisa@example.com",
    clientPhone: "+234 801 234 5684",
    serviceType: "DENTAL",
    providerId: "TH-SP-002",
    providerName: "Dr. Michael Chen",
    date: "2024-01-14",
    time: "10:00 AM",
    duration: 45,
    status: "CANCELLED",
    notes: "Client requested cancellation - reschedule to next week",
    createdAt: "2024-01-07T09:30:00Z",
  },
  {
    id: "8",
    autoGeneratedId: "TH-APT-008",
    clientId: "TH-CL-008",
    clientName: "James Taylor",
    clientEmail: "james@example.com",
    clientPhone: "+234 801 234 5685",
    serviceType: "NUTRITION",
    providerId: "TH-SP-006",
    providerName: "Dr. Lisa Anderson",
    date: "2024-01-17",
    time: "02:00 PM",
    duration: 60,
    status: "RESCHEDULED",
    notes: "Initial nutrition consultation - rescheduled from 01-16",
    createdAt: "2024-01-10T14:00:00Z",
  },
];

const serviceTypeLabels: Record<string, string> = {
  COUNSELLING: "Counselling",
  DENTAL: "Dental Care",
  GYM: "Fitness & Gym",
  SKINCARE: "Skin Care",
  REHAB: "Rehabilitation",
  NUTRITION: "Nutrition",
  ELITE: "Elite Sports",
  SPA: "Spa & Massage",
};

const statusColors: Record<string, string> = {
  PENDING: "bg-yellow-100 text-yellow-800",
  APPROVED: "bg-green-100 text-green-800",
  CANCELLED: "bg-red-100 text-red-800",
  COMPLETED: "bg-blue-100 text-blue-800",
  RESCHEDULED: "bg-purple-100 text-purple-800",
};

const AppointmentList = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [serviceFilter, setServiceFilter] = useState("all");
  const [currentPage, setCurrentPage] = useState(1);
  const [view, setView] = useState<"list" | "calendar">("list");
  const [appointments, setAppointments] = useState<Appointment[]>(mockAppointments);
  const [selectedAppointment, setSelectedAppointment] = useState<Appointment | null>(null);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isRescheduleDialogOpen, setIsRescheduleDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  
  // Edit form state
  const [editForm, setEditForm] = useState({
    date: "",
    time: "",
    duration: 60,
    notes: "",
  });

  // Reschedule form state
  const [rescheduleForm, setRescheduleForm] = useState({
    date: "",
    time: "",
    reason: "",
  });

  const itemsPerPage = 10;

  const filteredAppointments = appointments.filter((apt) => {
    const matchesSearch =
      apt.clientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      apt.autoGeneratedId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      apt.providerName.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === "all" || apt.status === statusFilter;
    const matchesService = serviceFilter === "all" || apt.serviceType === serviceFilter;
    return matchesSearch && matchesStatus && matchesService;
  });

  const totalPages = Math.ceil(filteredAppointments.length / itemsPerPage);
  const paginatedAppointments = filteredAppointments.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const handleApprove = (apt: Appointment) => {
    setAppointments((prev) =>
      prev.map((a) => (a.id === apt.id ? { ...a, status: "APPROVED" } : a))
    );
  };

  const handleReject = (apt: Appointment) => {
    setAppointments((prev) =>
      prev.map((a) => (a.id === apt.id ? { ...a, status: "CANCELLED" } : a))
    );
  };

  const handleComplete = (apt: Appointment) => {
    setAppointments((prev) =>
      prev.map((a) => (a.id === apt.id ? { ...a, status: "COMPLETED" } : a))
    );
  };

  const handleEdit = (apt: Appointment) => {
    setSelectedAppointment(apt);
    setEditForm({
      date: apt.date,
      time: apt.time,
      duration: apt.duration,
      notes: apt.notes || "",
    });
    setIsEditDialogOpen(true);
  };

  const handleReschedule = (apt: Appointment) => {
    setSelectedAppointment(apt);
    setRescheduleForm({
      date: apt.date,
      time: apt.time,
      reason: "",
    });
    setIsRescheduleDialogOpen(true);
  };

  const handleDelete = (apt: Appointment) => {
    setSelectedAppointment(apt);
    setIsDeleteDialogOpen(true);
  };

  const handleView = (apt: Appointment) => {
    setSelectedAppointment(apt);
    setIsViewDialogOpen(true);
  };

  const submitEdit = () => {
    if (selectedAppointment) {
      setAppointments((prev) =>
        prev.map((a) =>
          a.id === selectedAppointment.id
            ? {
                ...a,
                date: editForm.date,
                time: editForm.time,
                duration: editForm.duration,
                notes: editForm.notes,
              }
            : a
        )
      );
    }
    setIsEditDialogOpen(false);
  };

  const submitReschedule = () => {
    if (selectedAppointment) {
      setAppointments((prev) =>
        prev.map((a) =>
          a.id === selectedAppointment.id
            ? {
                ...a,
                date: rescheduleForm.date,
                time: rescheduleForm.time,
                status: "RESCHEDULED" as const,
              }
            : a
        )
      );
    }
    setIsRescheduleDialogOpen(false);
  };

  const submitDelete = () => {
    if (selectedAppointment) {
      setAppointments((prev) =>
        prev.filter((a) => a.id !== selectedAppointment.id)
      );
    }
    setIsDeleteDialogOpen(false);
  };

  return (
    <div className="p-6 lg:p-8 space-y-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl lg:text-3xl font-bold">Appointments</h1>
          <p className="text-muted-foreground mt-1">
            Manage all appointments with full CRUD operations
          </p>
        </div>
        <Button>
          <Plus className="w-4 h-4 mr-2" />
          Schedule New Appointment
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-5">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total</p>
                <p className="text-2xl font-bold">{appointments.length}</p>
              </div>
              <Calendar className="w-8 h-8 text-primary/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Pending</p>
                <p className="text-2xl font-bold text-yellow-600">
                  {appointments.filter((a) => a.status === "PENDING").length}
                </p>
              </div>
              <Clock className="w-8 h-8 text-yellow-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Approved</p>
                <p className="text-2xl font-bold text-green-600">
                  {appointments.filter((a) => a.status === "APPROVED").length}
                </p>
              </div>
              <Check className="w-8 h-8 text-green-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Completed</p>
                <p className="text-2xl font-bold text-blue-600">
                  {appointments.filter((a) => a.status === "COMPLETED").length}
                </p>
              </div>
              <Check className="w-8 h-8 text-blue-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Cancelled</p>
                <p className="text-2xl font-bold text-red-600">
                  {appointments.filter((a) => a.status === "CANCELLED").length}
                </p>
              </div>
              <X className="w-8 h-8 text-red-500/20" />
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search by client, provider, or appointment ID..."
                className="pl-9"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <div className="flex gap-2">
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger className="w-[150px]">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="PENDING">Pending</SelectItem>
                  <SelectItem value="APPROVED">Approved</SelectItem>
                  <SelectItem value="COMPLETED">Completed</SelectItem>
                  <SelectItem value="CANCELLED">Cancelled</SelectItem>
                  <SelectItem value="RESCHEDULED">Rescheduled</SelectItem>
                </SelectContent>
              </Select>
              <Select value={serviceFilter} onValueChange={setServiceFilter}>
                <SelectTrigger className="w-[180px]">
                  <SelectValue placeholder="Service Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Services</SelectItem>
                  <SelectItem value="COUNSELLING">Counselling</SelectItem>
                  <SelectItem value="DENTAL">Dental Care</SelectItem>
                  <SelectItem value="GYM">Fitness & Gym</SelectItem>
                  <SelectItem value="SPA">Spa & Massage</SelectItem>
                  <SelectItem value="SKINCARE">Skin Care</SelectItem>
                  <SelectItem value="REHAB">Rehabilitation</SelectItem>
                  <SelectItem value="NUTRITION">Nutrition</SelectItem>
                  <SelectItem value="ELITE">Elite Sports</SelectItem>
                </SelectContent>
              </Select>
              <div className="flex border rounded-lg">
                <Button
                  variant={view === "list" ? "default" : "ghost"}
                  size="icon"
                  onClick={() => setView("list")}
                >
                  <List className="w-4 h-4" />
                </Button>
                <Button
                  variant={view === "calendar" ? "default" : "ghost"}
                  size="icon"
                  onClick={() => setView("calendar")}
                >
                  <Grid3X3 className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Tabs value={view} onValueChange={(v) => setView(v as "list" | "calendar")}>
        <TabsList className="hidden">
          <TabsTrigger value="list">List</TabsTrigger>
          <TabsTrigger value="calendar">Calendar</TabsTrigger>
        </TabsList>

        <TabsContent value="list">
          <Card>
            <CardContent className="pt-6">
              <div className="rounded-md border">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Appointment</TableHead>
                      <TableHead>Client</TableHead>
                      <TableHead>Provider</TableHead>
                      <TableHead>Service</TableHead>
                      <TableHead>Date & Time</TableHead>
                      <TableHead>Duration</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {paginatedAppointments.map((apt) => (
                      <TableRow key={apt.id}>
                        <TableCell>
                          <div>
                            <p className="font-medium">{apt.autoGeneratedId}</p>
                            <p className="text-xs text-muted-foreground">
                              {new Date(apt.createdAt).toLocaleDateString()}
                            </p>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-3">
                            <Avatar>
                              <AvatarFallback className="bg-primary/10 text-primary">
                                {apt.clientName
                                  .split(" ")
                                  .map((n) => n[0])
                                  .join("")
                                  .toUpperCase()
                                  .slice(0, 2)}
                              </AvatarFallback>
                            </Avatar>
                            <div>
                              <p className="font-medium">{apt.clientName}</p>
                              <p className="text-xs text-muted-foreground">{apt.clientPhone}</p>
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <p className="font-medium">{apt.providerName}</p>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">
                            {serviceTypeLabels[apt.serviceType] || apt.serviceType}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Calendar className="w-4 h-4 text-muted-foreground" />
                            <span>{apt.date}</span>
                          </div>
                          <div className="flex items-center gap-2 text-sm text-muted-foreground">
                            <Clock className="w-3 h-3" />
                            <span>{apt.time}</span>
                          </div>
                        </TableCell>
                        <TableCell>{apt.duration} mins</TableCell>
                        <TableCell>
                          <Badge className={statusColors[apt.status]}>
                            {apt.status.charAt(0) + apt.status.slice(1).toLowerCase()}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            {apt.status === "PENDING" && (
                              <>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="text-green-600 hover:text-green-700 hover:bg-green-50"
                                  onClick={() => handleApprove(apt)}
                                  title="Approve"
                                >
                                  <Check className="w-4 h-4" />
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="text-red-600 hover:text-red-700 hover:bg-red-50"
                                  onClick={() => handleReject(apt)}
                                  title="Reject"
                                >
                                  <X className="w-4 h-4" />
                                </Button>
                              </>
                            )}
                            {apt.status === "APPROVED" && (
                              <Button
                                variant="ghost"
                                size="icon"
                                className="text-blue-600 hover:text-blue-700 hover:bg-blue-50"
                                onClick={() => handleComplete(apt)}
                                title="Mark Complete"
                              >
                                <Check className="w-4 h-4" />
                              </Button>
                            )}
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleView(apt)}
                              title="View Details"
                            >
                              <Eye className="w-4 h-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleEdit(apt)}
                              title="Edit"
                            >
                              <Edit className="w-4 h-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="text-purple-600 hover:text-purple-700 hover:bg-purple-50"
                              onClick={() => handleReschedule(apt)}
                              title="Reschedule"
                            >
                              <RefreshCw className="w-4 h-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="text-red-600 hover:text-red-700 hover:bg-red-50"
                              onClick={() => handleDelete(apt)}
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>

              {totalPages > 1 && (
                <div className="flex items-center justify-between mt-4">
                  <p className="text-sm text-muted-foreground">
                    Showing {((currentPage - 1) * itemsPerPage) + 1} to{" "}
                    {Math.min(currentPage * itemsPerPage, filteredAppointments.length)} of{" "}
                    {filteredAppointments.length} appointments
                  </p>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => setCurrentPage(currentPage - 1)}
                      disabled={currentPage === 1}
                    >
                      <ChevronLeft className="w-4 h-4" />
                    </Button>
                    {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                      <Button
                        key={page}
                        variant={currentPage === page ? "default" : "outline"}
                        size="icon"
                        onClick={() => setCurrentPage(page)}
                        className="w-8 h-8"
                      >
                        {page}
                      </Button>
                    ))}
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => setCurrentPage(currentPage + 1)}
                      disabled={currentPage === totalPages}
                    >
                      <ChevronRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="calendar">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Calendar View</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-7 gap-1">
                {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
                  <div key={day} className="text-center text-sm font-medium p-2">
                    {day}
                  </div>
                ))}
                {Array.from({ length: 35 }, (_, i) => {
                  const day = i - 2;
                  const isCurrentMonth = day > 0 && day <= 31;
                  const dayAppointments = isCurrentMonth
                    ? appointments.filter((a) => {
                        const aptDate = new Date(a.date);
                        return aptDate.getDate() === day;
                      })
                    : [];
                  return (
                    <div
                      key={i}
                      className={`min-h-[120px] p-2 border rounded-lg ${
                        isCurrentMonth ? "bg-card" : "bg-muted/30"
                      }`}
                    >
                      {isCurrentMonth && (
                        <>
                          <span className="text-sm font-medium">{day}</span>
                          <div className="mt-1 space-y-1">
                            {dayAppointments.slice(0, 3).map((apt) => (
                              <div
                                key={apt.id}
                                className={`text-xs p-1 rounded truncate ${statusColors[apt.status]}`}
                                title={`${apt.clientName} - ${apt.time}`}
                              >
                                {apt.clientName}
                              </div>
                            ))}
                            {dayAppointments.length > 3 && (
                              <div className="text-xs text-muted-foreground">
                                +{dayAppointments.length - 3} more
                              </div>
                            )}
                          </div>
                        </>
                      )}
                    </div>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* View Appointment Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Appointment Details</DialogTitle>
          </DialogHeader>
          {selectedAppointment && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-muted-foreground">Appointment ID</Label>
                  <p className="font-medium">{selectedAppointment.autoGeneratedId}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Status</Label>
                  <p>
                    <Badge className={statusColors[selectedAppointment.status]}>
                      {selectedAppointment.status}
                    </Badge>
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Client Name</Label>
                  <p className="font-medium">{selectedAppointment.clientName}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Client Email</Label>
                  <p className="font-medium">{selectedAppointment.clientEmail}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Client Phone</Label>
                  <p className="font-medium">{selectedAppointment.clientPhone}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Provider</Label>
                  <p className="font-medium">{selectedAppointment.providerName}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Service Type</Label>
                  <p className="font-medium">{serviceTypeLabels[selectedAppointment.serviceType]}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Duration</Label>
                  <p className="font-medium">{selectedAppointment.duration} minutes</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Date</Label>
                  <p className="font-medium">{selectedAppointment.date}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Time</Label>
                  <p className="font-medium">{selectedAppointment.time}</p>
                </div>
              </div>
              {selectedAppointment.notes && (
                <div>
                  <Label className="text-muted-foreground">Notes</Label>
                  <p className="font-medium">{selectedAppointment.notes}</p>
                </div>
              )}
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsViewDialogOpen(false)}>
              Close
            </Button>
            <Button variant="outline">
              <MessageSquare className="w-4 h-4 mr-2" />
              Message Client
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Appointment</DialogTitle>
            <DialogDescription>
              Update appointment details for {selectedAppointment?.clientName}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="edit-date">Date</Label>
                <Input
                  id="edit-date"
                  type="date"
                  value={editForm.date}
                  onChange={(e) => setEditForm({ ...editForm, date: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-time">Time</Label>
                <Input
                  id="edit-time"
                  type="time"
                  value={editForm.time}
                  onChange={(e) => setEditForm({ ...editForm, time: e.target.value })}
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="edit-duration">Duration (minutes)</Label>
              <Select
                value={editForm.duration.toString()}
                onValueChange={(v) => setEditForm({ ...editForm, duration: parseInt(v) })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="30">30 minutes</SelectItem>
                  <SelectItem value="45">45 minutes</SelectItem>
                  <SelectItem value="60">60 minutes</SelectItem>
                  <SelectItem value="90">90 minutes</SelectItem>
                  <SelectItem value="120">120 minutes</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="edit-notes">Notes</Label>
              <Textarea
                id="edit-notes"
                value={editForm.notes}
                onChange={(e) => setEditForm({ ...editForm, notes: e.target.value })}
                placeholder="Add appointment notes..."
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={submitEdit}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reschedule Dialog */}
      <Dialog open={isRescheduleDialogOpen} onOpenChange={setIsRescheduleDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reschedule Appointment</DialogTitle>
            <DialogDescription>
              Reschedule appointment for {selectedAppointment?.clientName}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="reschedule-date">New Date</Label>
                <Input
                  id="reschedule-date"
                  type="date"
                  value={rescheduleForm.date}
                  onChange={(e) => setRescheduleForm({ ...rescheduleForm, date: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="reschedule-time">New Time</Label>
                <Input
                  id="reschedule-time"
                  type="time"
                  value={rescheduleForm.time}
                  onChange={(e) => setRescheduleForm({ ...rescheduleForm, time: e.target.value })}
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="reschedule-reason">Reason for Rescheduling</Label>
              <Textarea
                id="reschedule-reason"
                value={rescheduleForm.reason}
                onChange={(e) => setRescheduleForm({ ...rescheduleForm, reason: e.target.value })}
                placeholder="Explain why this appointment needs to be rescheduled..."
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsRescheduleDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={submitReschedule}>
              <RefreshCw className="w-4 h-4 mr-2" />
              Reschedule
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Appointment</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this appointment? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          {selectedAppointment && (
            <div className="p-4 bg-muted rounded-lg">
              <div className="grid grid-cols-2 gap-2 text-sm">
                <span className="text-muted-foreground">Appointment ID:</span>
                <span className="font-medium">{selectedAppointment.autoGeneratedId}</span>
                <span className="text-muted-foreground">Client:</span>
                <span className="font-medium">{selectedAppointment.clientName}</span>
                <span className="text-muted-foreground">Date:</span>
                <span className="font-medium">{selectedAppointment.date}</span>
                <span className="text-muted-foreground">Time:</span>
                <span className="font-medium">{selectedAppointment.time}</span>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDeleteDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={submitDelete}>
              <Trash2 className="w-4 h-4 mr-2" />
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default AppointmentList;
