import { useState } from "react";
import { Link } from "react-router-dom";
import { ComingSoon } from "@/components/ui/ComingSoon";
import {
  TrendingUp,
  TrendingDown,
  Calendar,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  ChevronRight,
  Activity,
  Heart,
  Dumbbell,
  Sparkles,
  Brain,
  Salad,
  Scissors,
  Phone,
  Mail,
  MessageSquare,
  FileText,
  User,
  ArrowRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";

// Client progress type
interface ClientProgress {
  id: string;
  clientId: string;
  autoGeneratedId: string;
  fullName: string;
  email: string;
  phone: string;
  serviceType: string;
  assignedProvider: string;
  enrollmentDate: string;
  status: "ACTIVE" | "COMPLETED" | "PAUSED" | "CANCELLED";
  overallProgress: number;
  lastAppointment: string;
  nextAppointment: string;
  goals: string[];
  achievements: string[];
  appointments: AppointmentRecord[];
  notes: ProgressNote[];
}

interface AppointmentRecord {
  id: string;
  date: string;
  type: string;
  status: "COMPLETED" | "CANCELLED" | "RESCHEDULED";
  notes?: string;
}

interface ProgressNote {
  id: string;
  date: string;
  author: string;
  content: string;
  type: "UPDATE" | "MILESTONE" | "CONCERN" | "ACHIEVEMENT";
}

// Mock data
const mockClientProgress: ClientProgress[] = [
  {
    id: "1",
    clientId: "TH-CL-001",
    autoGeneratedId: "TH-CL-001",
    fullName: "John Doe",
    email: "john@example.com",
    phone: "+234 801 234 5678",
    serviceType: "COUNSELLING",
    assignedProvider: "Dr. Sarah Johnson",
    enrollmentDate: "2023-11-01",
    status: "ACTIVE",
    overallProgress: 75,
    lastAppointment: "2024-01-14",
    nextAppointment: "2024-01-21",
    goals: ["Reduce anxiety levels", "Improve sleep quality", "Develop coping strategies"],
    achievements: ["Completed 5 sessions", "Improved sleep by 40%", "Learned 3 coping techniques"],
    appointments: [
      { id: "a1", date: "2024-01-14", type: "Session 6", status: "COMPLETED", notes: "Good progress on breathing exercises" },
      { id: "a2", date: "2024-01-07", type: "Session 5", status: "COMPLETED", notes: "Introduced mindfulness techniques" },
      { id: "a3", date: "2023-12-31", type: "Session 4", status: "COMPLETED" },
      { id: "a4", date: "2023-12-24", type: "Session 3", status: "COMPLETED" },
      { id: "a5", date: "2023-12-17", type: "Session 2", status: "COMPLETED" },
      { id: "a6", date: "2023-12-10", type: "Session 1", status: "COMPLETED", notes: "Initial assessment completed" },
    ],
    notes: [
      { id: "n1", date: "2024-01-14", author: "Dr. Sarah Johnson", content: "Patient showing excellent progress with anxiety management techniques.", type: "UPDATE" },
      { id: "n2", date: "2024-01-07", author: "Dr. Sarah Johnson", content: "Reached milestone: 5 sessions completed!", type: "MILESTONE" },
    ],
  },
  {
    id: "2",
    clientId: "TH-CL-002",
    autoGeneratedId: "TH-CL-002",
    fullName: "Jane Smith",
    email: "jane@example.com",
    phone: "+234 801 234 5679",
    serviceType: "DENTAL",
    assignedProvider: "Dr. Michael Chen",
    enrollmentDate: "2023-10-15",
    status: "ACTIVE",
    overallProgress: 60,
    lastAppointment: "2024-01-12",
    nextAppointment: "2024-01-26",
    goals: ["Complete teeth whitening", "Address gum sensitivity", "Establish regular cleaning schedule"],
    achievements: ["Completed initial assessment", "Started whitening treatment"],
    appointments: [
      { id: "a7", date: "2024-01-12", type: "Whitening Session 2", status: "COMPLETED" },
      { id: "a8", date: "2024-01-05", type: "Whitening Session 1", status: "COMPLETED" },
      { id: "a9", date: "2023-12-20", type: "Cleaning", status: "COMPLETED" },
      { id: "a10", date: "2023-11-25", type: "Initial Consultation", status: "COMPLETED" },
    ],
    notes: [
      { id: "n3", date: "2024-01-12", author: "Dr. Michael Chen", content: "Whitening results are visible. Patient satisfied with progress.", type: "UPDATE" },
    ],
  },
  {
    id: "3",
    clientId: "TH-CL-003",
    autoGeneratedId: "TH-CL-003",
    fullName: "Mike Johnson",
    email: "mike@example.com",
    phone: "+234 801 234 5680",
    serviceType: "GYM",
    assignedProvider: "Coach James Williams",
    enrollmentDate: "2023-09-01",
    status: "ACTIVE",
    overallProgress: 85,
    lastAppointment: "2024-01-15",
    nextAppointment: "2024-01-16",
    goals: ["Lose 15kg", "Build muscle mass", "Improve cardiovascular endurance"],
    achievements: ["Lost 10kg", "Increased bench press by 20kg", "Completed 50 sessions"],
    appointments: [
      { id: "a11", date: "2024-01-15", type: "Personal Training", status: "COMPLETED" },
      { id: "a12", date: "2024-01-13", type: "Cardio Session", status: "COMPLETED" },
      { id: "a13", date: "2024-01-11", type: "Personal Training", status: "COMPLETED" },
    ],
    notes: [
      { id: "n4", date: "2024-01-15", author: "Coach James Williams", content: "Excellent progress! Only 5kg away from goal weight.", type: "MILESTONE" },
      { id: "n5", date: "2024-01-10", author: "Coach James Williams", content: "New personal best on deadlift: 100kg", type: "ACHIEVEMENT" },
    ],
  },
  {
    id: "4",
    clientId: "TH-CL-004",
    autoGeneratedId: "TH-CL-004",
    fullName: "Sarah Williams",
    email: "sarah@example.com",
    phone: "+234 801 234 5681",
    serviceType: "SPA",
    assignedProvider: "Therapist Maria Garcia",
    enrollmentDate: "2023-12-01",
    status: "ACTIVE",
    overallProgress: 45,
    lastAppointment: "2024-01-10",
    nextAppointment: "2024-01-17",
    goals: ["Reduce stress levels", "Improve skin condition", "Establish self-care routine"],
    achievements: ["Completed 8 sessions", "Reported better sleep"],
    appointments: [
      { id: "a14", date: "2024-01-10", type: "Aromatherapy Massage", status: "COMPLETED" },
      { id: "a15", date: "2024-01-03", type: "Deep Tissue Massage", status: "COMPLETED" },
      { id: "a16", date: "2023-12-27", type: "Swedish Massage", status: "COMPLETED" },
    ],
    notes: [
      { id: "n6", date: "2024-01-10", author: "Therapist Maria Garcia", content: "Stress levels significantly reduced. Patient reports feeling more relaxed.", type: "UPDATE" },
    ],
  },
  {
    id: "5",
    clientId: "TH-CL-005",
    autoGeneratedId: "TH-CL-005",
    fullName: "Emily Brown",
    email: "emily@example.com",
    phone: "+234 801 234 5682",
    serviceType: "SKINCARE",
    assignedProvider: "Dr. Emily Brown",
    enrollmentDate: "2023-11-15",
    status: "COMPLETED",
    overallProgress: 100,
    lastAppointment: "2024-01-08",
    nextAppointment: "-",
    goals: ["Clear acne scarring", "Improve skin texture", "Establish skincare routine"],
    achievements: ["Completed treatment plan", "100% improvement in skin texture", "Clear skin achieved"],
    appointments: [
      { id: "a17", date: "2024-01-08", type: "Follow-up", status: "COMPLETED", notes: "Treatment completed successfully" },
      { id: "a18", date: "2023-12-15", type: "Chemical Peel", status: "COMPLETED" },
      { id: "a19", date: "2023-11-29", type: "Facial Treatment", status: "COMPLETED" },
    ],
    notes: [
      { id: "n7", date: "2024-01-08", author: "Dr. Emily Brown", content: "Treatment goals achieved! Patient satisfied.", type: "ACHIEVEMENT" },
    ],
  },
];

const serviceLabels: Record<string, string> = {
  COUNSELLING: "Counselling",
  DENTAL: "Dental Care",
  GYM: "Fitness & Gym",
  SKINCARE: "Skin Care",
  REHAB: "Rehabilitation",
  NUTRITION: "Nutrition",
  ELITE: "Elite Sports",
  SPA: "Spa & Massage",
};

const serviceIcons: Record<string, React.ElementType> = {
  COUNSELLING: Brain,
  DENTAL: Activity,
  GYM: Dumbbell,
  SKINCARE: Scissors,
  REHAB: Activity,
  NUTRITION: Salad,
  ELITE: Activity,
  SPA: Sparkles,
};

const statusColors: Record<string, string> = {
  ACTIVE: "bg-green-100 text-green-800",
  COMPLETED: "bg-blue-100 text-blue-800",
  PAUSED: "bg-yellow-100 text-yellow-800",
  CANCELLED: "bg-red-100 text-red-800",
};

const noteTypeColors: Record<string, string> = {
  UPDATE: "bg-blue-100 text-blue-800",
  MILESTONE: "bg-purple-100 text-purple-800",
  CONCERN: "bg-red-100 text-red-800",
  ACHIEVEMENT: "bg-green-100 text-green-800",
};

const ClientProgressTracking = () => {
  const [selectedClient, setSelectedClient] = useState<ClientProgress | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [serviceFilter, setServiceFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  const filteredClients = mockClientProgress.filter((client) => {
    const matchesService = serviceFilter === "all" || client.serviceType === serviceFilter;
    const matchesStatus = statusFilter === "all" || client.status === statusFilter;
    return matchesService && matchesStatus;
  });

  const handleViewProgress = (client: ClientProgress) => {
    setSelectedClient(client);
    setIsDialogOpen(true);
  };

  // Calculate stats
  const totalClients = mockClientProgress.length;
  const activeClients = mockClientProgress.filter((c) => c.status === "ACTIVE").length;
  const completedClients = mockClientProgress.filter((c) => c.status === "COMPLETED").length;
  const avgProgress = Math.round(
    mockClientProgress.reduce((sum, c) => sum + c.overallProgress, 0) / totalClients
  );

  return (
    <div className="relative p-6 lg:p-8 space-y-6">
      <ComingSoon
        title="Client Progress Tracking"
        description="Progress analytics per client are under development. This will be available once the backend exposes progress and session history endpoints."
      />
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl lg:text-3xl font-bold">Client Progress</h1>
          <p className="text-muted-foreground mt-1">
            Track and monitor client progress across all services
          </p>
        </div>
        <div className="flex gap-2">
          <Select value={serviceFilter} onValueChange={setServiceFilter}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Service Type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Services</SelectItem>
              <SelectItem value="COUNSELLING">Counselling</SelectItem>
              <SelectItem value="DENTAL">Dental Care</SelectItem>
              <SelectItem value="GYM">Fitness & Gym</SelectItem>
              <SelectItem value="SKINCARE">Skin Care</SelectItem>
              <SelectItem value="REHAB">Rehabilitation</SelectItem>
              <SelectItem value="NUTRITION">Nutrition</SelectItem>
              <SelectItem value="ELITE">Elite Sports</SelectItem>
              <SelectItem value="SPA">Spa & Massage</SelectItem>
            </SelectContent>
          </Select>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              <SelectItem value="ACTIVE">Active</SelectItem>
              <SelectItem value="COMPLETED">Completed</SelectItem>
              <SelectItem value="PAUSED">Paused</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Clients</p>
                <p className="text-2xl font-bold">{totalClients}</p>
              </div>
              <User className="w-8 h-8 text-primary/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Active Clients</p>
                <p className="text-2xl font-bold text-green-600">{activeClients}</p>
              </div>
              <Activity className="w-8 h-8 text-green-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Completed</p>
                <p className="text-2xl font-bold text-blue-600">{completedClients}</p>
              </div>
              <CheckCircle className="w-8 h-8 text-blue-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Avg Progress</p>
                <p className="text-2xl font-bold">{avgProgress}%</p>
              </div>
              <TrendingUp className="w-8 h-8 text-yellow-500/20" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Client Progress Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {filteredClients.map((client) => {
          const Icon = serviceIcons[client.serviceType] || Activity;
          return (
            <Card key={client.id} className="hover:shadow-lg transition-shadow">
              <CardContent className="pt-6">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <Avatar>
                      <AvatarFallback className="bg-primary/10 text-primary">
                        {client.fullName
                          .split(" ")
                          .map((n) => n[0])
                          .join("")
                          .toUpperCase()
                          .slice(0, 2)}
                      </AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-semibold">{client.fullName}</p>
                      <p className="text-sm text-muted-foreground">{client.autoGeneratedId}</p>
                    </div>
                  </div>
                  <Badge className={statusColors[client.status]}>
                    {client.status.charAt(0) + client.status.slice(1).toLowerCase()}
                  </Badge>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center gap-2 text-sm">
                    <Icon className="w-4 h-4 text-muted-foreground" />
                    <span>{serviceLabels[client.serviceType]}</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <User className="w-4 h-4" />
                    <span>{client.assignedProvider}</span>
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between text-sm">
                      <span>Overall Progress</span>
                      <span className="font-medium">{client.overallProgress}%</span>
                    </div>
                    <Progress value={client.overallProgress} className="h-2" />
                  </div>

                  <div className="grid grid-cols-2 gap-2 text-sm pt-2">
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Calendar className="w-4 h-4" />
                      <span>Last: {new Date(client.lastAppointment).toLocaleDateString()}</span>
                    </div>
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Calendar className="w-4 h-4" />
                      <span>Next: {client.nextAppointment === "-" ? "None" : new Date(client.nextAppointment).toLocaleDateString()}</span>
                    </div>
                  </div>
                </div>

                <Button
                  variant="outline"
                  className="w-full mt-4"
                  onClick={() => handleViewProgress(client)}
                >
                  View Full Progress
                  <ChevronRight className="w-4 h-4 ml-2" />
                </Button>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Client Details Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Client Progress Details</DialogTitle>
          </DialogHeader>
          {selectedClient && (
            <div className="space-y-6">
              {/* Client Info */}
              <div className="flex items-start gap-4">
                <Avatar className="w-16 h-16">
                  <AvatarFallback className="bg-primary/10 text-primary text-xl">
                    {selectedClient.fullName
                      .split(" ")
                      .map((n) => n[0])
                      .join("")
                      .toUpperCase()
                      .slice(0, 2)}
                  </AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold">{selectedClient.fullName}</h3>
                  <p className="text-muted-foreground">{selectedClient.autoGeneratedId}</p>
                  <div className="flex items-center gap-2 mt-2">
                    <Badge variant="outline">{serviceLabels[selectedClient.serviceType]}</Badge>
                    <Badge className={statusColors[selectedClient.status]}>
                      {selectedClient.status.charAt(0) + selectedClient.status.slice(1).toLowerCase()}
                    </Badge>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-3xl font-bold text-primary">{selectedClient.overallProgress}%</p>
                  <p className="text-sm text-muted-foreground">Overall Progress</p>
                </div>
              </div>

              <Tabs defaultValue="overview" className="w-full">
                <TabsList className="grid w-full grid-cols-4">
                  <TabsTrigger value="overview">Overview</TabsTrigger>
                  <TabsTrigger value="appointments">Appointments</TabsTrigger>
                  <TabsTrigger value="goals">Goals</TabsTrigger>
                  <TabsTrigger value="notes">Notes</TabsTrigger>
                </TabsList>

                <TabsContent value="overview" className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <Card>
                      <CardHeader>
                        <CardTitle className="text-lg">Assigned Provider</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <p className="font-medium">{selectedClient.assignedProvider}</p>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardHeader>
                        <CardTitle className="text-lg">Enrollment Date</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <p className="font-medium">
                          {new Date(selectedClient.enrollmentDate).toLocaleDateString()}
                        </p>
                      </CardContent>
                    </Card>
                  </div>

                  <Card>
                    <CardHeader>
                      <CardTitle className="text-lg">Goals</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-2">
                        {selectedClient.goals.map((goal, index) => (
                          <li key={index} className="flex items-center gap-2">
                            <ArrowRight className="w-4 h-4 text-primary" />
                            <span>{goal}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardHeader>
                      <CardTitle className="text-lg">Achievements</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-2">
                        {selectedClient.achievements.map((achievement, index) => (
                          <li key={index} className="flex items-center gap-2">
                            <CheckCircle className="w-4 h-4 text-green-500" />
                            <span>{achievement}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="appointments">
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-lg">Appointment History</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="rounded-md border">
                        <Table>
                          <TableHeader>
                            <TableRow>
                              <TableHead>Date</TableHead>
                              <TableHead>Type</TableHead>
                              <TableHead>Status</TableHead>
                              <TableHead>Notes</TableHead>
                            </TableRow>
                          </TableHeader>
                          <TableBody>
                            {selectedClient.appointments.map((apt) => (
                              <TableRow key={apt.id}>
                                <TableCell>{new Date(apt.date).toLocaleDateString()}</TableCell>
                                <TableCell>{apt.type}</TableCell>
                                <TableCell>
                                  <Badge
                                    className={
                                      apt.status === "COMPLETED"
                                        ? "bg-green-100 text-green-800"
                                        : apt.status === "CANCELLED"
                                        ? "bg-red-100 text-red-800"
                                        : "bg-yellow-100 text-yellow-800"
                                    }
                                  >
                                    {apt.status.charAt(0) + apt.status.slice(1).toLowerCase()}
                                  </Badge>
                                </TableCell>
                                <TableCell>{apt.notes || "-"}</TableCell>
                              </TableRow>
                            ))}
                          </TableBody>
                        </Table>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="goals">
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-lg">Goals Progress</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        {selectedClient.goals.map((goal, index) => {
                          const progress = Math.min(
                            selectedClient.overallProgress + Math.random() * 20 - 10,
                            100
                          );
                          return (
                            <div key={index} className="space-y-2">
                              <div className="flex items-center justify-between">
                                <span className="font-medium">{goal}</span>
                                <span className="text-sm text-muted-foreground">
                                  {Math.round(progress)}%
                                </span>
                              </div>
                              <Progress value={progress} className="h-2" />
                            </div>
                          );
                        })}
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="notes">
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-lg">Progress Notes</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        {selectedClient.notes.map((note) => (
                          <div key={note.id} className="p-4 border rounded-lg">
                            <div className="flex items-center justify-between mb-2">
                              <div className="flex items-center gap-2">
                                <Badge className={noteTypeColors[note.type]}>
                                  {note.type.charAt(0) + note.type.slice(1).toLowerCase()}
                                </Badge>
                                <span className="font-medium">{note.author}</span>
                              </div>
                              <span className="text-sm text-muted-foreground">
                                {new Date(note.date).toLocaleDateString()}
                              </span>
                            </div>
                            <p className="text-sm">{note.content}</p>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              </Tabs>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
              Close
            </Button>
            <Button>
              <MessageSquare className="w-4 h-4 mr-2" />
              Message Provider
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default ClientProgressTracking;
