import { useState } from "react";
import { Link } from "react-router-dom";
import { ComingSoon } from "@/components/ui/ComingSoon";
import {
  Plus,
  Search,
  Filter,
  MoreVertical,
  Eye,
  Edit,
  Trash2,
  User,
  Mail,
  Phone,
  MapPin,
  Stethoscope,
  Activity,
  Heart,
  Dumbbell,
  Sparkles,
  Scissors,
  Salad,
  Brain,
  ChevronLeft,
  ChevronRight,
  MessageSquare,
  Calendar,
  Link as LinkIcon,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";

// Service provider type
interface ServiceProvider {
  id: string;
  autoGeneratedId: string;
  fullName: string;
  email: string;
  phone: string;
  profession: string;
  specialty: string;
  location: string;
  status: "ACTIVE" | "INACTIVE" | "PENDING";
  assignedClients: number;
  totalClients: number;
  rating: number;
  joinedAt: string;
}

interface AssignedClient {
  id: string;
  clientName: string;
  serviceType: string;
  appointmentDate: string;
  status: "ACTIVE" | "COMPLETED" | "PENDING";
  progress: number;
}

// Mock data
const mockServiceProviders: ServiceProvider[] = [
  {
    id: "1",
    autoGeneratedId: "TH-SP-001",
    fullName: "Dr. Sarah Johnson",
    email: "sarah.johnson@takehealth.com",
    phone: "+234 801 234 5678",
    profession: "COUNSELLING",
    specialty: "Mental Health Counseling",
    location: "Main Clinic - Lagos",
    status: "ACTIVE",
    assignedClients: 12,
    totalClients: 45,
    rating: 4.8,
    joinedAt: "2023-06-15",
  },
  {
    id: "2",
    autoGeneratedId: "TH-SP-002",
    fullName: "Dr. Michael Chen",
    email: "michael.chen@takehealth.com",
    phone: "+234 801 234 5679",
    profession: "DENTAL",
    specialty: "General Dentistry",
    location: "Dental Center - Abuja",
    status: "ACTIVE",
    assignedClients: 8,
    totalClients: 32,
    rating: 4.9,
    joinedAt: "2023-08-20",
  },
  {
    id: "3",
    autoGeneratedId: "TH-SP-003",
    fullName: "Coach James Williams",
    email: "james.williams@takehealth.com",
    phone: "+234 801 234 5680",
    profession: "GYM",
    specialty: "Personal Fitness Training",
    location: "Fitness Center - Lagos",
    status: "ACTIVE",
    assignedClients: 15,
    totalClients: 58,
    rating: 4.7,
    joinedAt: "2023-05-10",
  },
  {
    id: "4",
    autoGeneratedId: "TH-SP-004",
    fullName: "Dr. Emily Brown",
    email: "emily.brown@takehealth.com",
    phone: "+234 801 234 5681",
    profession: "SKINCARE",
    specialty: "Medical Aesthetics",
    location: "Skin Care Clinic - Lagos",
    status: "ACTIVE",
    assignedClients: 6,
    totalClients: 24,
    rating: 4.6,
    joinedAt: "2023-09-01",
  },
  {
    id: "5",
    autoGeneratedId: "TH-SP-005",
    fullName: "Therapist Robert Taylor",
    email: "robert.taylor@takehealth.com",
    phone: "+234 801 234 5682",
    profession: "REHAB",
    specialty: "Physical Rehabilitation",
    location: "Rehab Center - Port Harcourt",
    status: "PENDING",
    assignedClients: 0,
    totalClients: 18,
    rating: 4.5,
    joinedAt: "2023-10-15",
  },
  {
    id: "6",
    autoGeneratedId: "TH-SP-006",
    fullName: "Dr. Lisa Anderson",
    email: "lisa.anderson@takehealth.com",
    phone: "+234 801 234 5683",
    profession: "NUTRITION",
    specialty: "Clinical Nutrition",
    location: "Wellness Center - Lagos",
    status: "ACTIVE",
    assignedClients: 10,
    totalClients: 40,
    rating: 4.8,
    joinedAt: "2023-07-22",
  },
  {
    id: "7",
    autoGeneratedId: "TH-SP-007",
    fullName: "Coach David Wilson",
    email: "david.wilson@takehealth.com",
    phone: "+234 801 234 5684",
    profession: "ELITE",
    specialty: "Sports Performance",
    location: "Elite Sports Center - Lagos",
    status: "ACTIVE",
    assignedClients: 5,
    totalClients: 20,
    rating: 4.9,
    joinedAt: "2023-04-05",
  },
  {
    id: "8",
    autoGeneratedId: "TH-SP-008",
    fullName: "Therapist Maria Garcia",
    email: "maria.garcia@takehealth.com",
    phone: "+234 801 234 5685",
    profession: "SPA",
    specialty: "Massage Therapy",
    location: "Spa & Wellness - Lagos",
    status: "ACTIVE",
    assignedClients: 9,
    totalClients: 35,
    rating: 4.7,
    joinedAt: "2023-08-10",
  },
];

const mockAssignedClients: Record<string, AssignedClient[]> = {
  "1": [
    { id: "c1", clientName: "John Doe", serviceType: "COUNSELLING", appointmentDate: "2024-01-15", status: "ACTIVE", progress: 75 },
    { id: "c2", clientName: "Jane Smith", serviceType: "COUNSELLING", appointmentDate: "2024-01-16", status: "PENDING", progress: 30 },
    { id: "c3", clientName: "Mike Johnson", serviceType: "COUNSELLING", appointmentDate: "2024-01-10", status: "COMPLETED", progress: 100 },
  ],
  "2": [
    { id: "c4", clientName: "Sarah Williams", serviceType: "DENTAL", appointmentDate: "2024-01-15", status: "ACTIVE", progress: 60 },
    { id: "c5", clientName: "Emily Brown", serviceType: "DENTAL", appointmentDate: "2024-01-17", status: "PENDING", progress: 20 },
  ],
  "3": [
    { id: "c6", clientName: "David Wilson", serviceType: "GYM", appointmentDate: "2024-01-15", status: "ACTIVE", progress: 85 },
    { id: "c7", clientName: "Lisa Anderson", serviceType: "GYM", appointmentDate: "2024-01-16", status: "ACTIVE", progress: 45 },
    { id: "c8", clientName: "James Taylor", serviceType: "GYM", appointmentDate: "2024-01-12", status: "COMPLETED", progress: 100 },
  ],
};

const professionLabels: Record<string, string> = {
  COUNSELLING: "Counselling",
  DENTAL: "Dental Care",
  GYM: "Fitness & Gym",
  SKINCARE: "Skin Care",
  REHAB: "Rehabilitation",
  NUTRITION: "Nutrition",
  ELITE: "Elite Sports",
  SPA: "Spa & Massage",
};

const professionIcons: Record<string, React.ElementType> = {
  COUNSELLING: Brain,
  DENTAL: Activity,
  GYM: Dumbbell,
  SKINCARE: Scissors,
  REHAB: Activity,
  NUTRITION: Salad,
  ELITE: Activity,
  SPA: Sparkles,
};

const statusColors: Record<string, string> = {
  ACTIVE: "bg-green-100 text-green-800",
  INACTIVE: "bg-gray-100 text-gray-800",
  PENDING: "bg-yellow-100 text-yellow-800",
};

const ServiceProviderManagement = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [professionFilter, setProfessionFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [currentPage, setCurrentPage] = useState(1);
  const [selectedProvider, setSelectedProvider] = useState<ServiceProvider | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isAssignDialogOpen, setIsAssignDialogOpen] = useState(false);
  const itemsPerPage = 10;

  const filteredProviders = mockServiceProviders.filter((provider) => {
    const matchesSearch =
      provider.fullName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      provider.email.toLowerCase().includes(searchQuery.toLowerCase()) ||
      provider.autoGeneratedId.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesProfession =
      professionFilter === "all" || provider.profession === professionFilter;
    const matchesStatus = statusFilter === "all" || provider.status === statusFilter;
    return matchesSearch && matchesProfession && matchesStatus;
  });

  const totalPages = Math.ceil(filteredProviders.length / itemsPerPage);
  const paginatedProviders = filteredProviders.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const handleViewProvider = (provider: ServiceProvider) => {
    setSelectedProvider(provider);
    setIsDialogOpen(true);
  };

  const handleAssignClient = (provider: ServiceProvider) => {
    setSelectedProvider(provider);
    setIsAssignDialogOpen(true);
  };

  const getAssignedClients = (providerId: string) => {
    return mockAssignedClients[providerId] || [];
  };

  return (
    <div className="relative p-6 lg:p-8 space-y-6">
      <ComingSoon
        title="Service Provider Management"
        description="This module is under development. Provider profiles, assignments, and scheduling will be available once the backend API is ready."
      />
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl lg:text-3xl font-bold">Service Providers</h1>
          <p className="text-muted-foreground mt-1">
            Manage doctors, therapists, and assign them to clients
          </p>
        </div>
        <Button>
          <Plus className="w-4 h-4 mr-2" />
          Add New Provider
        </Button>
      </div>

      {/* Quick Stats */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Providers</p>
                <p className="text-2xl font-bold">{mockServiceProviders.length}</p>
              </div>
              <User className="w-8 h-8 text-primary/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Active Providers</p>
                <p className="text-2xl font-bold">
                  {mockServiceProviders.filter((p) => p.status === "ACTIVE").length}
                </p>
              </div>
              <Stethoscope className="w-8 h-8 text-green-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Assignments</p>
                <p className="text-2xl font-bold">
                  {mockServiceProviders.reduce((sum, p) => sum + p.assignedClients, 0)}
                </p>
              </div>
              <LinkIcon className="w-8 h-8 text-blue-500/20" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Pending Approval</p>
                <p className="text-2xl font-bold">
                  {mockServiceProviders.filter((p) => p.status === "PENDING").length}
                </p>
              </div>
              <Calendar className="w-8 h-8 text-yellow-500/20" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search by name, email, or ID..."
                className="pl-9"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <div className="flex gap-2">
              <Select value={professionFilter} onValueChange={setProfessionFilter}>
                <SelectTrigger className="w-[180px]">
                  <SelectValue placeholder="Profession" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Professions</SelectItem>
                  <SelectItem value="COUNSELLING">Counselling</SelectItem>
                  <SelectItem value="DENTAL">Dental Care</SelectItem>
                  <SelectItem value="GYM">Fitness & Gym</SelectItem>
                  <SelectItem value="SKINCARE">Skin Care</SelectItem>
                  <SelectItem value="REHAB">Rehabilitation</SelectItem>
                  <SelectItem value="NUTRITION">Nutrition</SelectItem>
                  <SelectItem value="ELITE">Elite Sports</SelectItem>
                  <SelectItem value="SPA">Spa & Massage</SelectItem>
                </SelectContent>
              </Select>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger className="w-[150px]">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="ACTIVE">Active</SelectItem>
                  <SelectItem value="INACTIVE">Inactive</SelectItem>
                  <SelectItem value="PENDING">Pending</SelectItem>
                </SelectContent>
              </Select>
              <Button variant="outline" size="icon">
                <Filter className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Service Provider Table */}
      <Card>
        <CardHeader className="pb-4">
          <CardTitle className="text-lg">Service Provider List</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Provider</TableHead>
                  <TableHead>Profession</TableHead>
                  <TableHead>Location</TableHead>
                  <TableHead>Clients</TableHead>
                  <TableHead>Rating</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="w-[50px]"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {paginatedProviders.map((provider) => {
                  const Icon = professionIcons[provider.profession] || User;
                  return (
                    <TableRow key={provider.id}>
                      <TableCell>
                        <div className="flex items-center gap-3">
                          <Avatar>
                            <AvatarFallback className="bg-primary/10 text-primary">
                              {provider.fullName
                                .split(" ")
                                .map((n) => n[0])
                                .join("")
                                .toUpperCase()
                                .slice(0, 2)}
                            </AvatarFallback>
                          </Avatar>
                          <div>
                            <p className="font-medium">{provider.fullName}</p>
                            <p className="text-sm text-muted-foreground">{provider.autoGeneratedId}</p>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Icon className="w-4 h-4 text-muted-foreground" />
                          <span>{professionLabels[provider.profession]}</span>
                        </div>
                        <p className="text-sm text-muted-foreground">{provider.specialty}</p>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <MapPin className="w-4 h-4 text-muted-foreground" />
                          <span>{provider.location}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">
                            {provider.assignedClients} / {provider.totalClients}
                          </p>
                          <p className="text-sm text-muted-foreground">assigned</p>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1">
                          <span className="text-yellow-500">★</span>
                          <span>{provider.rating.toFixed(1)}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                            statusColors[provider.status]
                          }`}
                        >
                          {provider.status.charAt(0) + provider.status.slice(1).toLowerCase()}
                        </span>
                      </TableCell>
                      <TableCell>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon">
                              <MoreVertical className="w-4 h-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuLabel>Actions</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem onClick={() => handleViewProvider(provider)}>
                              <Eye className="w-4 h-4 mr-2" />
                              View Details
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => handleAssignClient(provider)}>
                              <LinkIcon className="w-4 h-4 mr-2" />
                              Assign Client
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                              <MessageSquare className="w-4 h-4 mr-2" />
                              Send Message
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                              <Calendar className="w-4 h-4 mr-2" />
                              View Schedule
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem>
                              <Edit className="w-4 h-4 mr-2" />
                              Edit Provider
                            </DropdownMenuItem>
                            <DropdownMenuItem className="text-destructive">
                              <Trash2 className="w-4 h-4 mr-2" />
                              Deactivate
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between mt-4">
              <p className="text-sm text-muted-foreground">
                Showing {((currentPage - 1) * itemsPerPage) + 1} to{" "}
                {Math.min(currentPage * itemsPerPage, filteredProviders.length)} of{" "}
                {filteredProviders.length} providers
              </p>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setCurrentPage(currentPage - 1)}
                  disabled={currentPage === 1}
                >
                  <ChevronLeft className="w-4 h-4" />
                </Button>
                {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                  <Button
                    key={page}
                    variant={currentPage === page ? "default" : "outline"}
                    size="icon"
                    onClick={() => setCurrentPage(page)}
                    className="w-8 h-8"
                  >
                    {page}
                  </Button>
                ))}
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setCurrentPage(currentPage + 1)}
                  disabled={currentPage === totalPages}
                >
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Provider Details Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Service Provider Details</DialogTitle>
          </DialogHeader>
          {selectedProvider && (
            <div className="space-y-6">
              {/* Provider Info */}
              <div className="flex items-start gap-4">
                <Avatar className="w-16 h-16">
                  <AvatarFallback className="bg-primary/10 text-primary text-xl">
                    {selectedProvider.fullName
                      .split(" ")
                      .map((n) => n[0])
                      .join("")
                      .toUpperCase()
                      .slice(0, 2)}
                  </AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold">{selectedProvider.fullName}</h3>
                  <p className="text-muted-foreground">{selectedProvider.autoGeneratedId}</p>
                  <div className="flex items-center gap-2 mt-2">
                    <Badge variant="outline">{professionLabels[selectedProvider.profession]}</Badge>
                    <span
                      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                        statusColors[selectedProvider.status]
                      }`}
                    >
                      {selectedProvider.status.charAt(0) + selectedProvider.status.slice(1).toLowerCase()}
                    </span>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-muted-foreground">Email</Label>
                  <p className="font-medium flex items-center gap-2">
                    <Mail className="w-4 h-4" />
                    {selectedProvider.email}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Phone</Label>
                  <p className="font-medium flex items-center gap-2">
                    <Phone className="w-4 h-4" />
                    {selectedProvider.phone}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Specialty</Label>
                  <p className="font-medium">{selectedProvider.specialty}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Location</Label>
                  <p className="font-medium flex items-center gap-2">
                    <MapPin className="w-4 h-4" />
                    {selectedProvider.location}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Joined</Label>
                  <p className="font-medium">{new Date(selectedProvider.joinedAt).toLocaleDateString()}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Rating</Label>
                  <p className="font-medium flex items-center gap-1">
                    <span className="text-yellow-500">★</span>
                    {selectedProvider.rating.toFixed(1)}
                  </p>
                </div>
              </div>

              {/* Assigned Clients */}
              <div className="border-t pt-6">
                <h4 className="font-semibold mb-4">Assigned Clients</h4>
                <div className="space-y-3">
                  {getAssignedClients(selectedProvider.id).map((client) => (
                    <div
                      key={client.id}
                      className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50"
                    >
                      <div className="flex items-center gap-3">
                        <Avatar>
                          <AvatarFallback className="bg-primary/10 text-primary">
                            {client.clientName
                              .split(" ")
                              .map((n) => n[0])
                              .join("")
                              .toUpperCase()
                              .slice(0, 2)}
                          </AvatarFallback>
                        </Avatar>
                        <div>
                          <p className="font-medium">{client.clientName}</p>
                          <p className="text-sm text-muted-foreground">
                            {professionLabels[client.serviceType]} • {client.appointmentDate}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <div className="text-right">
                          <p className="text-sm font-medium">{client.progress}%</p>
                          <p className="text-xs text-muted-foreground">Progress</p>
                        </div>
                        <Badge
                          className={
                            client.status === "ACTIVE"
                              ? "bg-green-100 text-green-800"
                              : client.status === "COMPLETED"
                              ? "bg-blue-100 text-blue-800"
                              : "bg-yellow-100 text-yellow-800"
                          }
                        >
                          {client.status}
                        </Badge>
                        <Button variant="outline" size="sm">
                          View Progress
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
              Close
            </Button>
            <Button onClick={() => handleAssignClient(selectedProvider!)}>
              Assign Client
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Assign Client Dialog */}
      <Dialog open={isAssignDialogOpen} onOpenChange={setIsAssignDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Assign Client to {selectedProvider?.fullName}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium">Select Client</label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a client" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="john">John Doe - Counselling</SelectItem>
                  <SelectItem value="jane">Jane Smith - Dental</SelectItem>
                  <SelectItem value="mike">Mike Johnson - Fitness</SelectItem>
                  <SelectItem value="sarah">Sarah Williams - Spa</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="text-sm font-medium">Service Type</label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select service" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="counselling">Counselling</SelectItem>
                  <SelectItem value="dental">Dental Care</SelectItem>
                  <SelectItem value="gym">Fitness & Gym</SelectItem>
                  <SelectItem value="spa">Spa & Massage</SelectItem>
                  <SelectItem value="skincare">Skin Care</SelectItem>
                  <SelectItem value="rehab">Rehabilitation</SelectItem>
                  <SelectItem value="nutrition">Nutrition</SelectItem>
                  <SelectItem value="elite">Elite Sports</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="text-sm font-medium">Appointment Date</label>
              <Input type="date" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsAssignDialogOpen(false)}>
              Cancel
            </Button>
            <Button>Assign Client</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

// Helper component for labels
const Label = ({ children, className }: { children: React.ReactNode; className?: string }) => (
  <p className={`text-sm ${className}`}>{children}</p>
);

export default ServiceProviderManagement;
